name: core
description: "Stone dApp core library"
version: 0.0.1
publish_to: none
homepage:

environment:
  sdk: '>=3.7.0 <4.0.0'
  flutter: ">=3.24.3"

dependencies:
  flutter:
    sdk: flutter
  dependencies:
    path: ../dependencies

  solana:
    path: ../building_blocks/solana
  web3dart: ^2.7.3
  lottie: ^3.1.2
  image: ^4.2.0
  collection: ^1.18.0
  timeago: ^3.7.0

dev_dependencies:
  mockito: ^5.4.4
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  build_runner:

flutter: